project:
  type: website
  output-dir: docs

website:
  title: "gurpreet-kaur-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: imdb-project/portfolio_final.qmd
        text: "IMDb Movie Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source